# This file stores configurations for your Shopify app.

scopes = "write_products,write_customers,write_draft_orders,read_orders,write_fulfillments,write_orders,write_assigned_fulfillment_orders,write_merchant_managed_fulfillment_orders,write_third_party_fulfillment_orders"
